### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by tlnagy** [mkitti/Napari.jl#26] opened 2022-06-21 00:13 UTC
https://github.com/mkitti/Napari.jl/commit/b836278698df9ef22a899a02de1934ba90ceb842 bumped the compatible OMETIFF versions, but a new version of Napari was never tagged so Napari v0.2.0 is holding OMETIFF.jl back.

```julia
ERROR: Unsatisfiable requirements detected for package OMETIFF [2d0ec36b]:                                                                                                                       
 OMETIFF [2d0ec36b] log:                                                                                                                                                                         
 ├─possible versions are: 0.2.0-0.4.1 or uninstalled                                                                                                                                             
 ├─restricted to versions 0.4 by an explicit requirement, leaving only versions 0.4.0-0.4.1                                                                                                      
 └─restricted by compatibility requirements with Napari [ed46c112] to versions: 0.3.0-0.3.14 — no versions left                                                                                  
   └─Napari [ed46c112] log:                                                                     
     ├─possible versions are: 0.1.0-0.2.0 or uninstalled                                        
     └─restricted to versions 0.2.0 by an explicit requirement, leaving only versions 0.2.0    
```

Do you mind registering the current main branch?

**Comment by mkitti** [comment] 2022-06-21 00:28
Done: https://github.com/mkitti/Napari.jl/releases/tag/v0.2.1

**Comment by mkitti** [comment] 2022-06-21 00:46
Pull request merged to the General registry: https://github.com/JuliaRegistries/General/pull/62748

Feel free to reopen if the issue is not solved.

**Comment by tlnagy** [comment] 2022-06-21 00:47
thanks!

**Closed as completed by mkitti** 2022-06-21 00:46 UTC
